apiVersion: v1
kind: Secret
metadata:
  name: field-service-secret
  namespace: nll-scheduler
type: Opaque
stringData:
  POSTGRES_PASSWORD: "nll-password-field"
  DATABASE_URL: "postgres://field_user:nll-password-field@localhost:5432/field_db?sslmode=disable"
