apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedule-service-postgres-pvc
  namespace: nll-scheduler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
