apiVersion: v1
kind: Secret
metadata:
  name: schedule-service-secret
  namespace: nll-scheduler
type: Opaque
stringData:
  POSTGRES_PASSWORD: "nll-password-schedule"
  DATABASE_URL: "postgres://schedule_user:nll-password-schedule@localhost:5432/schedule_db?sslmode=disable"
  SCHEDULER_ENGINE_URL: "http://scheduler-engine:8080"
