apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: team-service-postgres-pvc
  namespace: nll-scheduler-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
