apiVersion: v1
kind: Service
metadata:
  name: team-service
  namespace: nll-scheduler
  labels:
    app: team-service
spec:
  selector:
    app: team-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
